{
  "id": "CVE-2022-48565",
  "published": "2023-08-22T19:16:32",
  "modified": "2023-12-06T01:02:44.333162",
  "details": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "repo_url": "https://github.com/python/cpython",
  "cwes": [],
  "commits": [
    "88db37442238079a2eff4d142e8e94cfddb58e22"
  ]
}
