{
  "id": "PSF-2023-5",
  "published": "2023-08-24T00:00:00",
  "modified": "2023-12-06T01:02:44.393257",
  "details": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
  "summary": "XML External Entity issue in plistlib module",
  "repo_url": "https://github.com/python/cpython",
  "cwes": [],
  "commits": [
    "3a833f748fc629d25a5af3faeef91447f4709804",
    "c1004b85464579771db3b50f5b150449275bbbd0",
    "dfa645a65ec0788d98851130a217e029d1cc4e9b"
  ]
}
