{
  "id": "CVE-2019-16227",
  "published": "2019-09-11T15:15:11",
  "modified": "2024-04-22T22:56:23.269458",
  "details": "An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "repo_url": "https://github.com/jnwatson/py-lmdb",
  "cwes": [],
  "commits": [
    "2765beed9c72816d6ff4aa42bb25aa293a4c915e"
  ]
}
