{
  "id": "CVE-2019-19588",
  "published": "2019-12-05T01:15:14",
  "modified": "2023-11-29T06:20:28.538707",
  "details": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "repo_url": "https://github.com/kvesteri/validators",
  "cwes": [],
  "commits": [
    "34d355e87168241e872b25811d245810df2bd430"
  ]
}
