{
  "id": "CVE-2022-42731",
  "published": "2022-10-11T14:15:10",
  "modified": "2025-07-02T00:22:29.543748",
  "details": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    }
  ],
  "repo_url": "https://github.com/mkalioby/django-mfa2",
  "cwes": [],
  "commits": [
    "4903967c23e7dc515090c26bcacec2b64d8dbe9d"
  ]
}
