{
  "id": "CVE-2021-25287",
  "published": "2021-06-02T16:15:08",
  "modified": "2025-09-30T07:53:05.899734",
  "details": "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_graya_la.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
    }
  ],
  "repo_url": "https://github.com/python-pillow/pillow",
  "cwes": [],
  "commits": [
    "235a7d6d7deab9555dc2c1b42fdf11243f6080e8",
    "80d6137c860b9322572ee1390514df1975acb2e7"
  ]
}
