{
  "id": "CVE-2023-25399",
  "published": "2023-07-05T17:15:09",
  "modified": "2025-09-24T11:59:23.951911",
  "details": "A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function. Note: This is disputed as a bug and not a vulnerability. SciPy is not designed to be exposed to untrusted users or data directly.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "repo_url": "https://github.com/scipy/scipy",
  "cwes": [],
  "commits": [
    "7f208fa57f6470e2c428b91bbfc38ed86a7d5269"
  ]
}
