{
  "id": "PYSEC-2019-131",
  "published": "2019-11-26T15:15:00",
  "modified": "2023-11-08T04:01:28.229049",
  "details": "typed_ast 1.3.0 and 1.3.1 has an ast_for_arguments out-of-bounds read. An attacker with the ability to cause a Python interpreter to parse Python source (but not necessarily execute it) may be able to crash the interpreter process. This could be a concern, for example, in a web-based service that parses (but does not execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)",
  "repo_url": "https://github.com/python/typed_ast",
  "cwes": [],
  "commits": [
    "21f2eb1fddedbace2db3ec6324f42fc8a6c631e6"
  ]
}
