{
  "id": "CVE-2022-4767",
  "published": "2022-12-27T15:15:12",
  "modified": "2023-11-29T09:59:16.860913",
  "details": "Denial of Service in GitHub repository usememos/memos prior to 0.9.1.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "repo_url": "https://github.com/usememos/memos",
  "cwes": [],
  "commits": [
    "7ec22482c16bbcacfbfe369c216c022623601723"
  ]
}
